name: Deploy Pages 🚀

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
      - name: Install dependencies
        run: bun install
      - name: Compose Markdown index
        run: |
          chmod +x run.sh
          ./run.sh
      - name: Build
        run: bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  test:
    environment:
      name: testing
    runs-on: ubuntu-24.04
    needs: [deploy]
    steps:
      - name: Test deployed file
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/KAnggara75/KAnggara75.github.io/main/test.sh)"
